from django.urls import path, re_path
from . import views

urlpatterns = [
    path("api/connection/status", views.api_connection_status, name="connection_status"),
    path("api/conversations", views.api_conversations, name="api_conversations"),
    path("api/conversations/<int:pk>", views.api_conversation_detail, name="api_conversation_detail"),
    path("api/conversations/<int:pk>/mode", views.api_conversation_mode, name="api_conversation_mode"),
    path("api/conversations/<int:pk>/archive", views.api_conversation_archive, name="api_conversation_archive"),
    # re_path y no <int:pk>: el converter int de Django solo matchea [0-9]+,
    # asi que /api/messages/-1 (una conversacion de proyeccion) daria 404. El
    # resto de las rutas con <int:pk> se dejan como estan a proposito -- son
    # de escritura (modo humano, archivar, incidentes) y que un id negativo
    # ni siquiera matchee la ruta es una guarda mas.
    re_path(r"^api/messages/(?P<pk>-?\d+)$", views.api_messages, name="api_messages"),
    path("api/media/<int:pk>", views.api_media_file, name="api_media_file"),
    path("api/conversations/<int:pk>/incidents", views.api_incidents, name="api_incidents"),
    path("api/incidents/<int:pk>/status", views.api_incident_status, name="api_incident_status"),
    path("api/admin/send-message", views.api_send_message, name="api_send_message"),
    path("api/admin/bot-state", views.api_bot_state, name="api_bot_state"),
    path("api/admin/cliente-activo", views.api_cliente_activo, name="api_cliente_activo"),
    path("api/admin/prompt", views.api_prompt, name="api_prompt"),
    path("api/admin/prompt-versions", views.api_prompt_versions, name="api_prompt_versions"),
    path("api/admin/prompt-versions/restore", views.api_prompt_version_restore, name="api_prompt_version_restore"),
    path("api/admin/specialists", views.api_specialists, name="api_specialists"),
    path("api/admin/specialists/<int:pk>", views.api_specialist_detail, name="api_specialist_detail"),
    path("api/admin/test-scenarios", views.api_test_scenarios, name="api_test_scenarios"),
    path("api/admin/test-scenarios/<int:pk>", views.api_test_scenario_detail, name="api_test_scenario_detail"),
    path("api/admin/test-runs/trigger", views.api_test_run_trigger, name="api_test_run_trigger"),
    path("api/admin/test-runs", views.api_test_runs, name="api_test_runs"),
    path("api/admin/test-runs/<int:pk>", views.api_test_run_detail, name="api_test_run_detail"),
    path("api/admin/llm-config", views.api_llm_config, name="api_llm_config"),
    path("api/admin/scraping-llm-config", views.api_scraping_llm_config, name="api_scraping_llm_config"),
    path("api/admin/media-llm-config", views.api_media_llm_config, name="api_media_llm_config"),
    path("api/admin/dashboard", views.api_dashboard_data, name="api_dashboard_data"),
    path("api/admin/meta-stats", views.api_meta_stats, name="api_meta_stats"),
    path("api/admin/template-stats", views.api_template_stats, name="api_template_stats"),
    path("api/admin/scraping-sources", views.api_scraping_sources, name="api_scraping_sources"),
    path("api/admin/scraping-sources/<int:pk>", views.api_scraping_source_detail, name="api_scraping_source_detail"),
    path("api/admin/scraping-sources/<int:pk>/run", views.api_scraping_source_run, name="api_scraping_source_run"),
    path(
        "api/admin/scraping-sources/<int:pk>/detail", views.api_scraping_source_detail_info,
        name="api_scraping_source_detail_info",
    ),
    path("api/admin/reservas/<str:codigo>/enviar-recordatorio", views.api_enviar_recordatorio, name="api_enviar_recordatorio"),
    path("api/admin/encuestas/enviar-masivo", views.api_enviar_encuesta_masiva, name="api_enviar_encuesta_masiva"),
    path("api/admin/reservas", views.api_reservas, name="api_reservas"),
    path("api/admin/leads", views.api_leads, name="api_leads"),
    # Leads B2B de InTouch (LeadInTouch), NO el lead automotriz heredado de
    # arriba (LeadComercial). Ruta y vista distintas a proposito -- ver el
    # docstring de api_leads_intouch.
    path("api/leads", views.api_leads_intouch, name="api_leads_intouch"),
    path("api/leads/<int:lead_id>/reintentar", views.api_lead_reintentar,
         name="api_lead_reintentar"),
    path("api/admin/campanas", views.api_campanas, name="api_campanas"),
    path("api/admin/campanas/enviar", views.api_campana_enviar, name="api_campana_enviar"),
    path("api/admin/welcome", views.api_welcome, name="api_welcome"),
    path("api/admin/vacation", views.api_vacation, name="api_vacation"),
    path("api/admin/business-hours", views.api_business_hours, name="api_business_hours"),
    path("api/admin/quick-responses", views.api_quick_responses, name="api_quick_responses"),
    path("api/admin/quick-responses/<int:pk>", views.api_quick_response_detail, name="api_quick_response_detail"),
    path("api/admin/snippets", views.api_snippets, name="api_snippets"),
    path("api/admin/snippets/<int:pk>", views.api_snippet_detail, name="api_snippet_detail"),
    path("api/admin/filters", views.api_filters, name="api_filters"),
    path("api/admin/filters/<int:pk>", views.api_filter_detail, name="api_filter_detail"),
    path("api/admin/handoff", views.api_handoff, name="api_handoff"),
    path("api/admin/logs", views.api_logs, name="api_logs"),
    path("api/admin/logs/export", views.api_logs_export, name="api_logs_export"),
    path("api/admin/audit", views.api_audit, name="api_audit"),
]
