# Generated by Django 5.2.16 on 2026-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duracion_min', models.PositiveIntegerField(default=30)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=300)),
                ('horario_texto', models.CharField(blank=True, default='Lun-Vie 9:00-18:00', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('contacto', models.CharField(db_index=True, max_length=32)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_email', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.sucursal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
