# Generated by Django 5.2.16 on 2026-07-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_servicio_sucursal_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('estado', models.CharField(choices=[('corriendo', 'Corriendo'), ('ok', 'Ok'), ('error', 'Error')], default='corriendo', max_length=20)),
                ('paginas_procesadas', models.IntegerField(default=0)),
                ('error_detalle', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('texto', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bot.scraperun')),
            ],
        ),
    ]
