# Generated by Django 5.2.16 on 2026-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_scraperun_scrapedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
