# Generated by Django 5.2.16 on 2026-07-27 20:33

from django.db import migrations, models


def backfill_prompt_versions(apps, schema_editor):
    Setting = apps.get_model("bot", "Setting")
    CustomSpecialist = apps.get_model("bot", "CustomSpecialist")
    PromptVersion = apps.get_model("bot", "PromptVersion")

    for agente in ("agendamiento", "confirmacion", "faq"):
        try:
            value = Setting.objects.get(key=f"prompt_override_{agente}").value
        except Setting.DoesNotExist:
            continue
        if value:
            PromptVersion.objects.create(agente=agente, prompt=value, activa=True)

    for row in CustomSpecialist.objects.all():
        PromptVersion.objects.create(agente=f"custom:{row.slug}", prompt=row.prompt, activa=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_customspecialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(db_index=True, max_length=100)),
                ('prompt', models.TextField()),
                ('activa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_prompt_versions, migrations.RunPython.noop),
    ]
