# Generated by Django 5.2.16 on 2026-07-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_promptversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customspecialist',
            name='prompt',
        ),
    ]
