# Generated by Django 5.2.16 on 2026-08-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_customspecialist_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('frecuencia_horas', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scraperun',
            name='catalogo_extraido',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='paginas_con_error',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='bot.scrapingsource'),
        ),
    ]
