# Generated by Django 5.2.16 on 2026-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_backfill_scraping_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingsource',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
