# Generated by Django 5.2.17 on 2026-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_optout'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='secciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

