# Generated by Django 5.2.17 on 2026-08-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_scrapedpage_secciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lead_class',
            field=models.CharField(blank=True, choices=[('HOT', 'HOT'), ('WARM', 'WARM'), ('COLD', 'COLD')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='stage',
            field=models.CharField(blank=True, choices=[('nuevo', 'nuevo'), ('descubrimiento', 'descubrimiento'), ('calificacion', 'calificacion'), ('cotizacion', 'cotizacion'), ('simulacion', 'simulacion'), ('agenda', 'agenda'), ('handoff', 'handoff'), ('seguimiento', 'seguimiento'), ('reclamo', 'reclamo'), ('cerrado', 'cerrado')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, max_length=20)),
                ('otorgado', models.BooleanField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='bot.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
