# Generated by Django 5.2.17 on 2026-08-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_sucursal_latitud_sucursal_longitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinonimoDominio',
        ),
    ]
