# Generated by Django 5.2.17 on 2026-08-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_delete_sinonimodominio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedpage',
            options={'ordering': ['id']},
        ),
    ]
