# Generated by Django 5.2.17 on 2026-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_scrapedpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='es_documento',
            field=models.BooleanField(default=False),
        ),
    ]
