# Generated by Django 5.2.17 on 2026-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_scrapedpage_es_documento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('sucursal', 'fecha', 'hora'), name='unico_cupo_activo_por_sucursal_fecha_hora'),
        ),
    ]
