# Generated by Django 5.2.17 on 2026-08-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_reserva_unico_cupo_activo_por_sucursal_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaServicioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_satisfaccion_ejecutivo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p2_satisfaccion_visita', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p3_trabajos_correctos', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('no_se', 'No se')], default='', max_length=10)),
                ('p4_recomendaria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_send', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_servicio_tecnico', to='bot.campaignsend')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaVentaAutoNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_nota_general', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p1_motivo_nota_baja', models.TextField(blank=True, default='')),
                ('p2_dejo_parte_pago', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=10)),
                ('p2_motivo_no', models.CharField(blank=True, choices=[('no_ofrecieron', 'No le ofrecieron la opcion'), ('precio_tasacion', 'Precio tasacion no fue el esperado'), ('vendio_particular', 'Lo vendio particular o a otra empresa'), ('otro', 'Otro motivo')], default='', max_length=30)),
                ('p2_motivo_otro_texto', models.TextField(blank=True, default='')),
                ('p3_firmo_checklist', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=10)),
                ('p3_motivo_no', models.CharField(blank=True, choices=[('no_presentaron', 'No le presentaron el checklist al momento de la entrega'), ('no_quiso_o_sin_tiempo', 'No quiso firmarlo o no tuvo tiempo')], default='', max_length=30)),
                ('p3_observaciones', models.TextField(blank=True, default='')),
                ('p4_informaron_garantia', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=10)),
                ('p5_informaron_mantenciones', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_send', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_venta_auto_nuevo', to='bot.campaignsend')),
            ],
        ),
    ]
