# Generated by Django 5.2.17 on 2026-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_encuestaserviciotecnico_encuestaventaautonuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
