# Generated by Django 5.2.17 on 2026-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_message_media_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_msg_id__gt', '')), fields=('wa_msg_id',), name='unico_wa_msg_id_no_vacio'),
        ),
    ]
