# Generated by Django 5.2.17 on 2026-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_message_unico_wa_msg_id_no_vacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customspecialist',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculocatalogo',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='customspecialist',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='scrapingsource',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='customspecialist',
            constraint=models.UniqueConstraint(fields=('cliente', 'slug'), name='unico_slug_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='scrapingsource',
            constraint=models.UniqueConstraint(fields=('cliente', 'url'), name='unico_url_por_cliente'),
        ),
    ]
