# Generated by Django 5.2.17 on 2026-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_sucursal_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculocatalogo',
            name='condicion',
            field=models.CharField(choices=[('0km', '0km'), ('usado', 'Usado')], db_index=True, default='0km', max_length=10),
        ),
    ]
