# Generated by Django 5.2.17 on 2026-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_backfill_condicion_usado_por_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculocatalogo',
            name='precio_contado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculocatalogo',
            name='precio_financiado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculocatalogo',
            name='condicion',
            field=models.CharField(blank=True, choices=[('0km', '0km'), ('usado', 'Usado')], db_index=True, default='0km', max_length=10),
        ),
    ]
