# Generated by Django 5.2.17 on 2026-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_vehiculocatalogo_precio_contado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedpage',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
