# Generated by Django 5.2.17 on 2026-09-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_alter_scrapedpage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('marca', models.CharField(db_index=True, max_length=60)),
                ('modelo', models.CharField(db_index=True, max_length=80)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('anio', models.IntegerField(db_index=True)),
                ('km', models.IntegerField(db_index=True)),
                ('precio_lista', models.IntegerField(db_index=True)),
                ('precio_oferta', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tipo_vehiculo', models.CharField(db_index=True, max_length=30)),
                ('combustible', models.CharField(db_index=True, max_length=30)),
                ('transmision', models.CharField(max_length=40)),
                ('es_automatico', models.BooleanField(db_index=True, default=True)),
                ('traccion', models.CharField(blank=True, default='', max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('n_duenos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=40)),
                ('airbags', models.IntegerField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, default='', max_length=120)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=120)),
                ('disponibilidad', models.CharField(blank=True, db_index=True, default='Disponible', max_length=40)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('acepta_financiamiento', models.BooleanField(default=True)),
                ('acepta_parte_pago', models.BooleanField(default=True)),
                ('motor', models.CharField(blank=True, default='', max_length=120)),
                ('cilindrada', models.CharField(blank=True, default='', max_length=40)),
                ('potencia', models.CharField(blank=True, default='', max_length=60)),
                ('torque', models.CharField(blank=True, default='', max_length=60)),
                ('rendimiento', models.CharField(blank=True, default='', max_length=60)),
                ('seguridad', models.TextField(blank=True, default='')),
                ('conectividad', models.TextField(blank=True, default='')),
                ('confort', models.TextField(blank=True, default='')),
                ('equipamiento', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('link_ficha', models.URLField(blank=True, default='', max_length=300)),
                ('link_fotos', models.URLField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['precio_oferta', 'marca', 'modelo'],
            },
        ),
        migrations.AlterField(
            model_name='customspecialist',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapingsource',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculocatalogo',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='renault', max_length=20),
        ),
    ]
