# Generated by Django 5.2.17 on 2026-09-02 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_vehiculousado_alter_customspecialist_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('comuna', models.CharField(blank=True, default='', max_length=120)),
                ('vehiculo_interes', models.CharField(blank=True, default='', max_length=200)),
                ('vehiculo_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('pie_disponible', models.IntegerField(blank=True, null=True)),
                ('cuota_objetivo', models.IntegerField(blank=True, null=True)),
                ('plazo_compra', models.CharField(blank=True, default='', max_length=60)),
                ('tiene_parte_pago', models.BooleanField(blank=True, null=True)),
                ('vehiculo_actual', models.CharField(blank=True, default='', max_length=200)),
                ('intencion', models.CharField(blank=True, default='', max_length=60)),
                ('sentimiento', models.CharField(blank=True, default='', max_length=30)),
                ('urgencia', models.CharField(blank=True, default='', max_length=30)),
                ('temperatura', models.CharField(blank=True, choices=[('HOT', 'HOT'), ('WARM', 'WARM'), ('COLD', 'COLD')], default='', max_length=10)),
                ('lead_score', models.IntegerField(default=0)),
                ('proxima_accion', models.CharField(blank=True, default='', max_length=300)),
                ('resumen', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comercial', to='bot.conversation')),
            ],
            options={
                'ordering': ['-lead_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoPartePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=200)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=150)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('patente', models.CharField(blank=True, default='', max_length=12)),
                ('estado_general', models.CharField(blank=True, default='', max_length=120)),
                ('tiene_deuda', models.BooleanField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('solicitada', 'Tasacion solicitada'), ('contactado', 'Cliente contactado'), ('descartada', 'Descartada')], default='solicitada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_parte_pago', to='bot.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
