# Generated by Django 5.2.17 on 2026-09-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_leadcomercial_vehiculopartepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(db_index=True, max_length=50, unique=True)),
                ('template', models.CharField(blank=True, default='', max_length=100)),
                ('segmento', models.CharField(blank=True, default='', max_length=200)),
                ('objetivo', models.CharField(blank=True, default='', max_length=300)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('palabra_clave', models.CharField(blank=True, default='', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem')], db_index=True, default='cavem', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
