# Generated by Django 5.2.17 on 2026-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_campana'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignsend',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign_type', 'seguimiento_vehiculo')), fields=('contacto', 'campaign_type'), name='un_solo_seguimiento_por_contacto'),
        ),
    ]
