# Generated by Django 5.2.17 on 2026-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_campaignsend_un_solo_seguimiento_por_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='patente',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
