# Generated by Django 5.2.17 on 2026-09-03 20:53

from django.db import migrations, models

# Solo documentacion de dos columnas (help_text): `sqlmigrate` confirma que las
# dos operaciones son no-op, no tocan el schema. Va igual como migracion para
# que `makemigrations --check` siga limpio. El porque de cada texto esta en
# bot/models.py (LeadComercial) -- resumen: el LLM guardaba el plazo del credito
# en plazo_compra y dejaba vehiculo_codigo vacio (conversacion 29, 2026-09-03).


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_reserva_patente_reserva_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcomercial',
            name='plazo_compra',
            field=models.CharField(blank=True, default='', help_text="CUANDO piensa comprar el cliente (ej. 'este viernes', 'en 3 semanas'). NO es el plazo del financiamiento.", max_length=60),
        ),
        migrations.AlterField(
            model_name='leadcomercial',
            name='vehiculo_codigo',
            field=models.CharField(blank=True, default='', help_text='Codigo del stock (ej. US011). Lo resuelve el sistema desde vehiculo_interes.', max_length=20),
        ),
    ]
