# Generated by Django 5.2.17 on 2026-09-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_leadcomercial_help_text_plazo_y_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='cavem', max_length=20),
        ),
        migrations.AlterField(
            model_name='customspecialist',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapingsource',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculocatalogo',
            name='cliente',
            field=models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], db_index=True, default='renault', max_length=20),
        ),
    ]
