# Generated by Django 5.2.17 on 2026-09-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_cliente_intouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], default='intouch', max_length=20)),
                ('slug', models.SlugField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cuando_aplica', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'slug'), name='unico_modelo_operacion_por_cliente')],
            },
        ),
        migrations.CreateModel(
            name='SolucionInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], default='intouch', max_length=20)),
                ('slug', models.SlugField(max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('operacion', 'Diseño de operación'), ('agentes_ia', 'Agentes conversacionales con IA'), ('analitica', 'Analítica y control de calidad'), ('integracion', 'Integraciones')], max_length=20)),
                ('descripcion', models.TextField()),
                ('canales', models.JSONField(blank=True, default=list)),
                ('modelos_operacion', models.JSONField(blank=True, default=list)),
                ('requiere_evaluacion_tecnica', models.BooleanField(default=False, help_text='El prompt exige presentarla como sujeta a evaluación técnica.')),
                ('ejemplos_uso', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'slug'), name='unica_solucion_por_cliente')],
            },
        ),
    ]
