# Generated by Django 5.2.17 on 2026-09-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_catalogo_intouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=200)),
                ('correo', models.CharField(blank=True, default='', max_length=200)),
                ('empresa', models.CharField(blank=True, default='', max_length=200)),
                ('industria', models.CharField(blank=True, default='', max_length=120)),
                ('subtipo_automotriz', models.CharField(blank=True, choices=[('importador', 'Importador'), ('concesionario', 'Concesionario'), ('automotora', 'Automotora'), ('servicio_tecnico', 'Servicio Técnico'), ('rent_a_car', 'Rent a Car'), ('financiera', 'Financiera Automotriz'), ('otro', 'Otro')], default='', max_length=20)),
                ('cargo', models.CharField(blank=True, default='', max_length=120)),
                ('pais_ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('situacion_contact_center', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], default='', max_length=10)),
                ('tipo_contact_center', models.CharField(blank=True, choices=[('propio', 'Propio'), ('externalizado', 'Externalizado'), ('mixto', 'Mixto'), ('no_tiene', 'No tiene')], default='', max_length=15)),
                ('usa_ia_actualmente', models.BooleanField(blank=True, null=True)),
                ('canales_actuales', models.JSONField(blank=True, default=list)),
                ('volumen_interacciones', models.CharField(blank=True, default='', help_text='Como lo dijo el contacto, conservando período y unidad.', max_length=120)),
                ('necesidad_principal', models.TextField(blank=True, default='')),
                ('soluciones_interes', models.JSONField(blank=True, default=list)),
                ('intencion', models.CharField(blank=True, default='', max_length=200)),
                ('plazo_proyecto', models.CharField(blank=True, default='', max_length=120)),
                ('lead_score', models.CharField(blank=True, choices=[('HOT', 'HOT'), ('WARM', 'WARM'), ('COLD', 'COLD'), ('NO_CALIFICADO', 'No calificado')], default='', help_text='Lo escribe calcular_lead_score (código), nunca el LLM.', max_length=15)),
                ('solicita_consultoria', models.BooleanField(default=False)),
                ('solicita_contacto_humano', models.BooleanField(default=False)),
                ('resumen_conversacion', models.TextField(blank=True, default='')),
                ('siguiente_accion_recomendada', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('notificado_en', models.DateTimeField(blank=True, help_text='Cuándo se notificó como HOT. Sella la notificación para que no se repita en cada turno.', null=True)),
                ('despachado_en', models.DateTimeField(blank=True, help_text='Cuándo se despachó al destino externo. Nulo con LEAD_SINK=none, y nulo tras un fallo: un lead sin despachar tiene que ser visible.', null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_intouch', to='bot.conversation')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
    ]
