# Generated by Django 5.2.17 on 2026-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_lead_intouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadintouch',
            name='evento_id',
            field=models.CharField(blank=True, default='', help_text='El intento de despacho vigente. Se regenera cuando cambia el contenido, nunca en un reintento.', max_length=36),
        ),
        migrations.AddField(
            model_name='leadintouch',
            name='payload_hash',
            field=models.CharField(blank=True, default='', help_text='Hash del contenido de negocio del último evento abierto. Es cómo se decide si un cambio amerita un evento nuevo.', max_length=64),
        ),
        migrations.AddField(
            model_name='leadintouch',
            name='revision',
            field=models.PositiveIntegerField(default=0, help_text='Orden de los eventos de este lead. Sólo avanza.'),
        ),
    ]
