# Generated by Django 5.2.17 on 2026-09-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_lead_intouch_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadintouch',
            name='crm_contact_id',
            field=models.CharField(blank=True, default='', help_text='Id del contacto en el CRM, como lo devolvió el receptor. Es lo que permite ir del lead a su ficha sin adivinar.', max_length=40),
        ),
        migrations.AddField(
            model_name='leadintouch',
            name='crm_deal_id',
            field=models.CharField(blank=True, default='', help_text='Id de la oportunidad, si la política del CRM abrió una. Vacío es válido: un lead frío entra como contacto sin oportunidad.', max_length=40),
        ),
    ]
