# Generated by Django 5.2.17 on 2026-09-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_lead_intouch_ids_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadintouch',
            name='conflicto_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo el receptor marcó un conflicto de identidad (409). Nulo si nunca hubo uno, o si un evento nuevo lo limpió porque el contenido cambió y puede resolver la ambigüedad.', null=True),
        ),
        migrations.AddField(
            model_name='leadintouch',
            name='conflicto_motivo',
            field=models.TextField(blank=True, default='', help_text='El motivo del conflicto que informó el receptor, o un texto genérico si el cuerpo del 409 no traía uno.'),
        ),
    ]
