# Generated by Django 5.2.17 on 2026-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_lead_intouch_conflicto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucionintouch',
            name='cuando_recomendarla',
            field=models.TextField(blank=True, default='', help_text='Cuándo conviene ofrecer esta solución, en términos de lo que el contacto dice necesitar. Es el mapeo necesidad -> solución del documento comercial. Vive acá y no en el prompt porque el prompt se manda en CADA turno y esto sólo hace falta cuando el bot habla de soluciones -- y porque quien edita el catálogo no deberia tener que editar el prompt para cambiar cuándo se recomienda algo.'),
        ),
    ]
