# Generated by Django 5.2.17 on 2026-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_solucionintouch_cuando_recomendarla'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadintouch',
            name='preferencia_horaria',
            field=models.CharField(blank=True, default='', help_text='Día u horario que el contacto dijo que le acomoda para que lo contacten. NO es una hora agendada: no hay agenda integrada, y el prompt prohíbe comprometer una hora. Queda listo para cuando exista una agenda real.', max_length=120),
        ),
    ]
