# Generated by Django 5.2.17 on 2026-09-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_leadintouch_preferencia_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(choices=[('renault', 'Renault'), ('astara', 'Astara Retail'), ('cavem', 'Cavem'), ('intouch', 'InTouch')], default='intouch', max_length=20)),
                ('tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo'), ('direccion', 'Dirección')], max_length=10)),
                ('valor', models.CharField(max_length=300)),
                ('etiqueta', models.CharField(blank=True, default='', help_text='El rótulo con que el sitio lo publica, ej. «Recursos Humanos» o «Chile».', max_length=120)),
                ('fuente_url', models.URLField(max_length=500)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='bot.scrapingsource')),
            ],
            options={
                'ordering': ['tipo', 'etiqueta', 'valor'],
            },
        ),
    ]
