# Generated by Django 5.2.17 on 2026-08-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaDePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('corriendo', 'Corriendo'), ('completa', 'Completa'), ('interrumpida', 'Interrumpida'), ('error', 'Error')], default='corriendo', max_length=20)),
                ('disparada_por', models.CharField(max_length=150)),
                ('nombre_escenario_filtro', models.CharField(blank=True, max_length=200, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EscenarioDePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('persona', models.TextField()),
                ('objetivo', models.TextField()),
                ('criterios', models.JSONField(default=list)),
                ('fuente', models.TextField(blank=True, default='')),
                ('max_turns', models.IntegerField(default=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.BooleanField(null=True)),
                ('fallos', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, null=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='simulator.corridadeprueba')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='simulator.escenariodeprueba')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
